name: model_pred_shielding
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - ca-certificates=2025.9.9=h06a4308_0
  - certifi=2021.5.30=py36h06a4308_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.3=he6710b0_2
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=1.1.1w=h7f8727e_0
  - pip=21.2.2=py36h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.6.13=h12debd9_1
  - readline=8.3=hc2a1206_0
  - setuptools=58.0.4=py36h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.37.1=pyhd3eb1b0_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - charset-normalizer==2.0.12
      - cloudpickle==2.2.1
      - dataclasses==0.8
      - decorator==4.4.2
      - gym==0.26.2
      - gym-notices==0.1.0
      - idna==3.10
      - imageio==2.15.0
      - imageio-ffmpeg==0.5.1
      - importlib-metadata==4.8.3
      - importlib-resources==5.4.0
      - joblib==1.1.1
      - moviepy==1.0.3
      - numpy==1.19.5
      - pillow==8.4.0
      - proglog==0.1.12
      - pygame==2.1.0
      - requests==2.27.1
      - scikit-learn==0.24.2
      - scipy==1.5.4
      - sklearn==0.0
      - threadpoolctl==3.1.0
      - torch==1.10.2
      - tqdm==4.64.1
      - typing-extensions==4.1.1
      - urllib3==1.26.20
      - zipp==3.6.0
prefix: /home/triakshunn/miniconda3/envs/model_pred_shielding
